using UnityEngine;

[RequireComponent(typeof(CharacterController))]
public class ZombieFollow : MonoBehaviour
{
    public Transform player;
    public float moveSpeed = 2f;
    public float stopDistance = 1.5f;

    public float gravity = -20f;   // ðŸ”¥ Ø§Ù„Ø¬Ø§Ø°Ø¨ÙŠØ©
    private float yVelocity;

    private CharacterController controller;

    void Start()
    {
        controller = GetComponent<CharacterController>();
    }

    void Update()
    {
        if (player == null) return;

        // âœ… Ø¬Ø§Ø°Ø¨ÙŠØ©
        if (controller.isGrounded)
        {
            yVelocity = -2f; // ÙŠØ«Ø¨Ù‘Øª Ø¹Ù„Ù‰ Ø§Ù„Ø£Ø±Ø¶
        }
        else
        {
            yVelocity += gravity * Time.deltaTime;
        }

        Vector3 move = Vector3.zero;

        float distance = Vector3.Distance(transform.position, player.position);

        if (distance > stopDistance)
        {
            Vector3 dir = player.position - transform.position;
            dir.y = 0;
            dir.Normalize();

            // Ø¯ÙˆØ±Ø§Ù†
            transform.rotation = Quaternion.Slerp(
                transform.rotation,
                Quaternion.LookRotation(dir),
                8f * Time.deltaTime
            );

            move = dir * moveSpeed;
        }

        // Ø¯Ù…Ø¬ Ø§Ù„Ø­Ø±ÙƒØ© + Ø§Ù„Ø¬Ø§Ø°Ø¨ÙŠØ©
        move.y = yVelocity;

        controller.Move(move * Time.deltaTime);
    }
}